---
# project_name: helmchart-helper
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    dir: cmd
    id: helmchart-helper
    binary: helmchart-helper

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: ["binary"]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - homepage: 'https://github.com/sgaunet/helmchart-helper'
    description: ''
    directory: Formula
    commit_author:
      name: sgaunet
      email: 1552102+sgaunet@users.noreply.github.com
    repository:
      owner: sgaunet
      name: homebrew-tools
      # Token with 'repo' scope is required for pushing to a different repository
      token: '{{ .Env.HOMEBREW_TAP_TOKEN }}'
    url_template: 'https://github.com/sgaunet/helmchart-helper/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    install: |
      bin.install "{{ .ArtifactName }}" => "helmchart-helper"
    test: |
      system "#{bin}/helmchart-helper", "--help"
