apiVersion: v1
kind: ConfigMap
metadata:
  name: {{"{{"}} include "example.fullname" . {{"}}"}}
data:
  {{"{{"}}- range $k,$v := .Values.configuration {{"}}"}}
  {{"{{"}} $k {{"}}"}}: {{"{{"}} $v | quote {{"}}"}}
  {{"{{"}}- end {{"}}"}}
